//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_TowerTag : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerButton
        {
            get
            {
                return SteamVR_Actions.towerTag_TriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.towerTag_Pose;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerPull
        {
            get
            {
                return SteamVR_Actions.towerTag_TriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripButton
        {
            get
            {
                return SteamVR_Actions.towerTag_GripButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuButton
        {
            get
            {
                return SteamVR_Actions.towerTag_MenuButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadButton
        {
            get
            {
                return SteamVR_Actions.towerTag_TrackPadButton;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPadTouch
        {
            get
            {
                return SteamVR_Actions.towerTag_TrackPadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.towerTag_Haptic;
            }
        }
    }
}
