//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_towerTag_TriggerButton;
        
        private static SteamVR_Action_Pose p_towerTag_Pose;
        
        private static SteamVR_Action_Single p_towerTag_TriggerPull;
        
        private static SteamVR_Action_Boolean p_towerTag_GripButton;
        
        private static SteamVR_Action_Boolean p_towerTag_MenuButton;
        
        private static SteamVR_Action_Boolean p_towerTag_TrackPadButton;
        
        private static SteamVR_Action_Vector2 p_towerTag_TrackPadTouch;
        
        private static SteamVR_Action_Vibration p_towerTag_Haptic;
        
        public static SteamVR_Action_Boolean towerTag_TriggerButton
        {
            get
            {
                return SteamVR_Actions.p_towerTag_TriggerButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose towerTag_Pose
        {
            get
            {
                return SteamVR_Actions.p_towerTag_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Single towerTag_TriggerPull
        {
            get
            {
                return SteamVR_Actions.p_towerTag_TriggerPull.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean towerTag_GripButton
        {
            get
            {
                return SteamVR_Actions.p_towerTag_GripButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean towerTag_MenuButton
        {
            get
            {
                return SteamVR_Actions.p_towerTag_MenuButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean towerTag_TrackPadButton
        {
            get
            {
                return SteamVR_Actions.p_towerTag_TrackPadButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 towerTag_TrackPadTouch
        {
            get
            {
                return SteamVR_Actions.p_towerTag_TrackPadTouch.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vibration towerTag_Haptic
        {
            get
            {
                return SteamVR_Actions.p_towerTag_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.towerTag_TriggerButton,
                    SteamVR_Actions.towerTag_Pose,
                    SteamVR_Actions.towerTag_TriggerPull,
                    SteamVR_Actions.towerTag_GripButton,
                    SteamVR_Actions.towerTag_MenuButton,
                    SteamVR_Actions.towerTag_TrackPadButton,
                    SteamVR_Actions.towerTag_TrackPadTouch,
                    SteamVR_Actions.towerTag_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.towerTag_TriggerButton,
                    SteamVR_Actions.towerTag_Pose,
                    SteamVR_Actions.towerTag_TriggerPull,
                    SteamVR_Actions.towerTag_GripButton,
                    SteamVR_Actions.towerTag_MenuButton,
                    SteamVR_Actions.towerTag_TrackPadButton,
                    SteamVR_Actions.towerTag_TrackPadTouch};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.towerTag_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.towerTag_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.towerTag_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.towerTag_TriggerButton,
                    SteamVR_Actions.towerTag_GripButton,
                    SteamVR_Actions.towerTag_MenuButton,
                    SteamVR_Actions.towerTag_TrackPadButton};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.towerTag_TriggerPull};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.towerTag_TrackPadTouch};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.towerTag_TriggerButton,
                    SteamVR_Actions.towerTag_TriggerPull,
                    SteamVR_Actions.towerTag_GripButton,
                    SteamVR_Actions.towerTag_MenuButton,
                    SteamVR_Actions.towerTag_TrackPadButton,
                    SteamVR_Actions.towerTag_TrackPadTouch};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_towerTag_TriggerButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/TowerTag/in/TriggerButton")));
            SteamVR_Actions.p_towerTag_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/TowerTag/in/Pose")));
            SteamVR_Actions.p_towerTag_TriggerPull = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/TowerTag/in/TriggerPull")));
            SteamVR_Actions.p_towerTag_GripButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/TowerTag/in/GripButton")));
            SteamVR_Actions.p_towerTag_MenuButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/TowerTag/in/MenuButton")));
            SteamVR_Actions.p_towerTag_TrackPadButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/TowerTag/in/TrackPadButton")));
            SteamVR_Actions.p_towerTag_TrackPadTouch = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/TowerTag/in/TrackPadTouch")));
            SteamVR_Actions.p_towerTag_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/TowerTag/out/Haptic")));
        }
    }
}
